### ISSUE TITLE
Complete/revise/review platform handbook for 0.5.0

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#116]
- [x] Collect input from #10 (mark with green background, Ahmad, Monika)
- [x] Collect input #59 (mark with green background, Ahmad, Chris)
- [x] Collect input #91 (mark with green background, Monika)
- [x] X-Check input #109 (mark with green background, Ahmad, Alexander)
- [x] Collect input #111 (mark with green background, Ahmad, Alexander)
- [x] Check JDK 8 -> 11 in installation slides #35 (Ahmad)
- [x] Revise statistics, intro, conclusion (Holger)
- [x] Review/revise changes (Chris)
- [x] Add missing references (after submission)
- [x] Fork 0.5.0 release version, prepare 0.6.0 working version
- [x] On release version, remove danging/empty/incomplete section
- [x] On release version, replace reference keys by numbers
- [x] On release version, adjust page brakes, figure/caption overlapping, figure scaling
- [x] On release version, pre-flight export as PDF, check/fix reference errors
- [x] Prepare Zenodo release, reserve DOI (Holger)
- [x] On release version, include reserved DOI (Holger)
- [x] Create release version, upload to own cloud, announce to Anni (Holger)
- [x] Archive release version with model, figure PDF in SVN (as for the other releases)
- [x] Upload to Zenodo (Holger)
